# Generated by Django 3.0.3 on 2020-03-01 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedexam',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 775676), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 762449), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 762617), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 762418), verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 754392), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 757285), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 755524), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='plantest',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 764486), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='score',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 758747), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='sharenews',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 763905), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 754936), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 13, 21, 11, 757694), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='users',
            name='cmtnd_day_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 13, 21, 11, 759870), null=True, verbose_name='CMTND day create'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dad_birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 13, 21, 11, 759986), null=True, verbose_name="dad'birthday"),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 13, 21, 11, 759499), null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='users',
            name='mom_birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 13, 21, 11, 760065), null=True, verbose_name="mom'birthday"),
        ),
        migrations.AlterField(
            model_name='users',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 13, 21, 11, 760406), null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tutor_birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 13, 21, 11, 760253), null=True, verbose_name="mom'birthday"),
        ),
        migrations.AlterField(
            model_name='users',
            name='wife_husband_birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 1, 13, 21, 11, 760170), null=True, verbose_name="mom'birthday"),
        ),
    ]
